### ISSUE TITLE
"with" in TextConst

### ISSUE THREAD

**Issue by DanielGoehler** [markbrummel/vscode-allint#11]
In Pages and Tables an "with" within a TextConst, a Field Name or Caption should not show a warning.

**Comment by markbrummel** [comment]
Can you share an example? Not sure what you mean.

**Comment by DanielGoehler** [comment]
Example:
![2017-10-06_13-44-08](https://user-images.githubusercontent.com/9556549/31276516-86fb87f2-aa9c-11e7-95b5-418e55429e8a.png)

**Comment by markbrummel** [comment]
Ah. ;-)

**Comment by markbrummel** [comment]
Fixed. Thx. Should be in next build.
