### ISSUE TITLE
Codeunit local OnRun Variables

### ISSUE THREAD

**Issue by DanielGoehler** [markbrummel/vscode-allint#12]
In Codeunits local Variables in OnRun show the message:
> This Variable is declared both as global and local (NAV-Skills Clean Code)

In this my case there are no global Variables at all.

**Comment by markbrummel** [comment]
Yeah, I did a fix on that for table objects. They have a different structure. The linter is now smarter to detect if it is in a function. I'll leave the issue open until you can test.

**Comment by DanielGoehler** [comment]
Works perfect now
