### ISSUE TITLE
Hungarian Notation Check on Function Names?

### ISSUE THREAD

**Issue by DanielGoehler** [markbrummel/vscode-allint#14]
In my option the Hungarian Notation should not checked on Function Names.

![2017-10-05](https://user-images.githubusercontent.com/9556549/31202432-e682b7b2-a962-11e7-8968-97d29e352784.png)

**Comment by markbrummel** [comment]
Weird. I'll look into it.

The underscore is going to be checked in one of the next versions. Sorry. ;-)

**Comment by DanielGoehler** [comment]
Yes, that's our Hungarian Notation. Don't worry, I will disable this check until I find a solution to change that for the hole solution.

**Comment by DanielGoehler** [comment]
I used the debugger to figure it out. **REC** is part of RETURN**REC**EIPTHEADER. It is also not the function, but the first parameter. A fix in the Pull Request #22

**Comment by markbrummel** [comment]
Good catch.
