### ISSUE TITLE
False hits on Hungarian Notation

### ISSUE THREAD

**Issue by MikeGlue** [markbrummel/vscode-allint#2]
I'm seeing some false hits on the Hungarian Notation detection.

![cleancodeissue](https://user-images.githubusercontent.com/5204734/30175344-2f9ed82e-93cc-11e7-86fb-524d4295a6ca.png)

**Comment by markbrummel** [comment]
True. In fact, Hungarian Notation is always set to, well, true.

Sorry for that. I will fix it as soon as I get my Angular project to connect to NAV and read the Json from an OData webservice. I need that as part of the bigger project.

Thanks for testing and reporting.

**Comment by markbrummel** [comment]
Can you please remove the extension and install the new, renamed version? This should solve the issue.

Keep the ideas comming!

**Comment by MikeGlue** [comment]
Works great now!
