### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by DanielGoehler** [markbrummel/vscode-allint#23]
Other Visual Studio Code extensions have a **.gitignore** file (e.g. https://github.com/Gimly/vscode-matlab/blob/master/.gitignore), which ignores the folders **out** and **node_modules**. I recommend the same here, because the compiler result and the Node.js Modules should not be under source control.

**Comment by markbrummel** [comment]
Let me figure out how to do that. Great suggestion. Learning. ;-)

**Comment by markbrummel** [comment]
Done. Updated the file and removed the folders from git. Please check if this is what you meant and close the issue or add a new comment.

**Comment by DanielGoehler** [comment]
Perfect.
