### ISSUE TITLE
question: status bar explanation

### ISSUE THREAD

**Issue by MikeGlue** [markbrummel/vscode-allint#3]
Would you be able to provide info on what the status bar data means? Thanks.

Example:
![cleancodeissue2](https://user-images.githubusercontent.com/5204734/30175424-79c18122-93cc-11e7-8120-2a3424151592.png)

**Comment by markbrummel** [comment]
It should be intuituve I guess. ;-)

**Comment by markbrummel** [comment]
Updated the bar. Does it make sense now? Also added an explanation to the readme.

**Comment by MikeGlue** [comment]
Great. Makes perfect sense now!! Thanks!
