### ISSUE TITLE
Suggestion: QuickActions

### ISSUE THREAD

**Issue by DanielGoehler** [markbrummel/vscode-allint#30]
I'm not sure if this is possible, but it would be nice to have **QuickActions** for e.g. suppressing Warnings (#29), fixing Hungarian Notation or creating missing functions or ... 

The Project **TSLint** implement additionally a **server**. And as one part of that a Fixer, which can change code: https://github.com/Microsoft/vscode-tslint/blob/master/tslint-server/src/fixer.ts

Example from https://github.com/Microsoft/vscode/issues/10912 how this could look:
![fc2471d8-6a3d-11e6-9b03-2b1f97230121](https://user-images.githubusercontent.com/9556549/31588044-8b51e0ec-b1ec-11e7-8f7c-457f6b501c92.png)

**Comment by markbrummel** [comment]
I agree it would be nice. I tried to make the server run but I gave up after several hours and decided to focus on the model and implementation of some basic warnings.

Tobias Fenster also volunteered to help with the server. Maybe we should have a team skypecall to discuss what we want. If everybody attends NAV TechDays we can meet there too.

Let me know. I have more time now NAVUG is over, but I have to prepare my session for Antwerp also...

**Comment by DanielGoehler** [comment]
Yes, sure. E. g. I'm would be available for a Skype Call this Week on Wednesday and Thursday 17:00 or later. If other times are better, I'm sure I can arrange that too. I'm also on NAV TechDays from Wednesday (Pre-Conference Day 2) till Friday.

**Comment by markbrummel** [comment]
Thursday 17:00 would work. Let me organize a call and share the link

**Comment by markbrummel** [comment]
https://global.gotomeeting.com/join/498313861

**Comment by DanielGoehler** [comment]
I have tried to convert the current solution into the [Language Server Example](https://code.visualstudio.com/docs/extensions/example-language-server) in a new Branch: https://github.com/DanielGoehler/vscode-allint/tree/LanguageServer

The **Language Check** will be done from the **Server** and the **Status Bar** and the related checks will be done in the **Client**.

What's currently missing is **Configuration Parameter** will be ignored, **Refactor** and **Cleancode** are not transfered yet. In addition, some Code Cleanup should be done.

Now *F5* only lunches the debugger for the _Client_. For the _Server_ a extra Step is needed. I try to describe the **Setup** and **Debug** Process here: https://github.com/DanielGoehler/vscode-allint/tree/LanguageServer#prepare-development-setup

**Comment by DanielGoehler** [comment]
Just a reminder for me: Quick Action need [CodeActionProviders](https://github.com/hoovercj/vscode-extension-tutorial#commands-and-codeactionproviders)

**Comment by markbrummel** [comment]
Works for me. Let's discuss this tomorrow how we can merge this back into the main branch and release.

**Comment by DanielGoehler** [comment]
**First Draft:**
I took the **CodeActionProvider** from [vscode-spell-checker](https://github.com/Jason-Rev/vscode-spell-checker) and transferred it into **AlLint** for renaming the Result of the _VariableNameForUnderScore_-Check: https://github.com/DanielGoehler/vscode-allint/commit/49f6932453a7b860d8427469365c67705e22ed3d

![image](https://user-images.githubusercontent.com/9556549/31797270-beddb8f2-b52d-11e7-885d-f0a6e99b3354.png)

Only Problem now, I don’t know how to rename **Symbols** instead of just the **Text**. If anybody knows, would be glade to know.

Recommendation on the [vscode](https://github.com/Microsoft/vscode)-Project for questions: Post a question on [Stackoverflow](https://stackoverflow.com/questions/46839773/vscode-extension-rename-symbols), which I did.

**Comment by DanielGoehler** [comment]
Got the Solution from (Stackoverflow)[https://stackoverflow.com/questions/46839773/vscode-extension-rename-symbols].
