### ISSUE TITLE
Hungarian notation hits for event parameters

### ISSUE THREAD

**Issue by MikeGlue** [markbrummel/vscode-allint#4]
The Hungarian Notation check is showing hits for parameters used in event subscribers where we have no choice on the naming, because the signatures must be specifically named. It would be ideal if it recognized that this was an acceptable scenario.

Example:
![image](https://user-images.githubusercontent.com/5204734/30282321-f17ad650-96e2-11e7-8611-67da7f9f9611.png)

**Comment by markbrummel** [comment]
Fixed, and I made so much more cool functions. Please give me ideas so I can make the tool better.
